CREATE TABLE filesystems (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  uuid BLOB NOT NULL UNIQUE,
  creation_info BLOB NOT NULL,
	root_node INTEGER NOT NULL REFERENCES nodes(id)
);

CREATE TABLE synchros (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  uuid BLOB NOT NULL UNIQUE,
  name VARCHAR NOT NULL,
  local_fs INTEGER NOT NULL REFERENCES filesystems(id),
  remote_fs INTEGER NOT NULL REFERENCES filesystems(id),
  status VARCHAR NOT NULL,
  state VARCHAR NOT NULL
);

CREATE TABLE nodes (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  kind VARCHAR NOT NULL,
	state BLOB,
  size BIGINT,
	parent INTEGER REFERENCES nodes(id)
);
