name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup update nightly && rustup component add --toolchain nightly rustfmt
    - name: Spell Check Repo
      uses: crate-ci/typos@v1.29.4
    - name: Check doc
      env:
        RUSTDOCFLAGS: "-D warnings"
      run: cargo doc --no-deps
    - name: Format
      run: cargo +nightly fmt --check --all
    - name: Clippy
      run: cargo clippy --all-targets -- -Dwarnings
    - name: Find unused dependencies
      uses: bnjbvr/cargo-machete@v0.8.0
    - name: Run tests
      run: cargo test
