name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup update nightly && rustup component add --toolchain nightly rustfmt
    - name: Build
      run: cargo build
    - name: Format
      run: cargo +nightly fmt --check --all
    - name: Clippy
      run: cargo clippy --all-targets -- -Dwarnings
    - name: Run tests
      run: cargo test
